#!perl

=head1 NAME

  Network managment

=cut

use strict;
use warnings FATAL => 'all';
use POSIX qw(strftime);
use Abills::Base qw(in_array mk_unique_value date_format _bp);
use Abills::Filters qw(_mac_former dec2hex);
require Abills::Misc;
use Data::Dumper;
use Nms::db::Nms;
use SNMP;

our ($html,
  %lang,
  $admin,
  %conf,
  $db,
);

our $Nms = Nms->new( $db, $admin, \%conf );

SNMP::addMibDirs( '../../var/snmp/mibs' );
SNMP::addMibDirs( '../../var/snmp/mibs/private' );
#SNMP::initMib();

my %snmpparms;
$snmpparms{Version} = 2;
$snmpparms{UseEnums} = 1;
$snmpparms{Retries} = 1;
$snmpparms{UseSprintValue} = 1;
$snmpparms{Timeout} = 2000000;
$snmpparms{Community} = $conf{NMS_COMMUNITY_RO};

require Nms::util::CableTest;
require Nms::util::NmsTraps;

#**********************************************************

=head2 nms_obj()

=cut

#**********************************************************
sub nms_obj {
  
  my ($attr) = @_;
  
  $LIST_PARAMS{SORT} = $FORM{sort} || 1;
  if ($FORM{del}){
    $Nms->obj_del($FORM{del})
  }
  if ($FORM{SAVE}){
    $Nms->obj_add({
      ID           => $FORM{OBJ_ID},
      RW_COMMUNITY => $FORM{Rw_COMMUNITY},
      RO_COMMUNITY => $FORM{RO_COMMUNITY},
      STATUS       => $FORM{STATUS} || 0,
    })
  }
  
  my $oid_hash = $Nms->sysobjectid_list({LABEL => '_SHOW', LIST2HASH  => 'objectid,label'});
  my $so_index = get_function_index('sysobjectid_table');
  my $nms = $Nms->obj_list({
    IP           => $FORM{IP} || '_SHOW',
    NAS_NAME     => '_SHOW',
    SYS_NAME     => '_SHOW',
    SYS_LOCATION => '_SHOW',
    SYS_OBJECTID => '_SHOW',
    STATUS       => $attr->{STATUS} || $FORM{STATUS} || '_SHOW',
    RO_COMMUNITY => '_SHOW',
    RW_COMMUNITY => '_SHOW',
    NAS_ID       => '_SHOW',
    ID           => $FORM{ID} || $FORM{chg} || '_SHOW',
    PAGE_ROWS    => 1000000,
    COLS_NAME    => 1,
    %LIST_PARAMS,
  });
  
  if ( $FORM{SET} && $FORM{header} ) {
    return nms_snmp_set({
      ID    => $FORM{ID},
      LABEL => $FORM{SET},
      IID   => $FORM{IID},
      VALUE => $FORM{VAL}
    })
  }
  if ( $FORM{STAT} && $FORM{header} ) {
    return nms_snmp_stats({
      OBJ_ID => $FORM{ID},
      LABEL  => $FORM{STAT},
      IID    => $FORM{IID},
      MONIT  => $FORM{MONIT},
      DEL_TR => $FORM{DEL_TR},
      ADD_TR => $FORM{ADD_TR}
    })
  }
  if ( $FORM{LABEL} && $FORM{VALUE} ) {
    nms_snmp_set({
          ID    => $FORM{ID},
          LABEL => $FORM{LABEL},
          IID   => $FORM{IID},
          VALUE => $FORM{VALUE}
        })
  }
  if ( $FORM{chg} ) {
    print $html->form_main({
          	CONTENT =>  label_w_txt('IP', $nms->[0]->{ip}).
                        label_w_txt($lang{NAME}, $nms->[0]->{sysname}).
                        label_w_txt('SYS_LOCATION', $nms->[0]->{syslocation}).
                        label_w_txt('SYS_OBJECTID', $html->element('a', $oid_hash->{$nms->[0]->{sysobjectid}},
                        { href => "index.cgi?index=" . $so_index . "&SYSOBJECTID=" . $nms->[0]->{sysobjectid} })).
                        label_w_txt('RO_COMMUNITY', $nms->[0]->{ro_community}, {INP=>'input'}).
                        label_w_txt('RW_COMMUNITY', $nms->[0]->{rw_community}, {INP=>'input'}).
                        label_w_txt($lang{STATUS},$nms->[0]->{status} || 0, {
                          ID     =>'STATUS',
                          INP    =>'select',
                          SELECT => {
                            0 => $lang{ENABLED},
                            1 => $lang{DISABLED}
                          }
                        }).
                        label_w_txt(undef, $html->form_input( 'SAVE', $lang{CHANGE}, {
                            TYPE => 'SUBMIT'
                          }) . "	" .
      											$html->button($lang{CANCEL}, "index=$index$pages_qs", {class =>"btn btn-default"}),
      								  {RCOL => 3}),
      	    METHOD  => 'GET',
          	HIDDEN  => {
            				'index'    => $index,
            				'OBJ_ID'   => $FORM{chg} || '',
          				},
            class => 'form-horizontal'
        	});
    return 1;
  }

  if ($FORM{ID} || $FORM{IP}) {
    my $obj_id = $FORM{ID} || $nms->[0]->{id};
    $pages_qs .= "&ID=$obj_id";
    my @header_arr = ("$lang{MAIN}:index=$index&visual=INFO$pages_qs");
    my $oids = $Nms->oids_list({
      OBJECTID  => $nms->[0]->{sysobjectid},
      LABEL     => '_SHOW',
      SECTION   => '_SHOW',
      TYPE      => '_SHOW',
      VALUE     => '_SHOW',
      COLS_NAME => 1,
      GROUP     => 'section'
    });
    my @main_btn;
    foreach my $val (@$oids){
      push @header_arr, "$val->{section}:index=$index&visual=$val->{section}$pages_qs" if $val->{type} eq 'table';
      push @main_btn, $html->button( $lang{RESTART}, "index=$index$pages_qs&VALUE=$val->{label}&LABEL=$val->{label}",{
        CONFIRM   => "$lang{RESTART} $nms->[0]->{ip} ?",
        ICON      => 'glyphicon glyphicon-repeat text-danger',
        class     => 'btn btn-default'
      }) if $val->{section} eq 'reboot';
      push @main_btn, $html->button( $lang{SAVE}, "index=$index$pages_qs&VALUE=$val->{value}&LABEL=$val->{label}",{
        CONFIRM   => "$lang{SAVE} $lang{SETTINGS} $nms->[0]->{ip} ?",
        ICON      => 'glyphicon glyphicon-floppy-save text-info',
        class     => 'btn btn-default'
      }) if $val->{section} eq 'write';
    };
    if ( $Nms->triggers_list({ OBJ_ID => $obj_id }) ) {
      push @header_arr, "$lang{STATS}:index=$index&visual=STATS$pages_qs";
    }
    push @header_arr, "MIBs Browser:index=$index&visual=MIB_BR$pages_qs";
    
    my $buttons = $html->table_header( \@header_arr, { TABS => 1 } );
    if ($buttons) {
      my $obj_select = $html->form_select(
         'ID',
         {
           SELECTED => $attr->{ID} || $obj_id,
           SEL_LIST => $Nms->obj_list(
             {
               IP  => '_SHOW',
               SYS_LOCATION => '_SHOW',
               COLS_NAME => 1,
               SORT      => 1,
               PAGE_ROWS => 10000,
             }
           ),
           SEL_KEY        => 'id',
           SEL_VALUE      => 'ip,syslocation',
           NO_ID          => 1,
           MAIN_MENU      => $index,
           MAIN_MENU_ARGV => "chg=" . ($obj_id || '')
         }
       );
     
      my $obj_select_form = $html->form_main(
         {
           CONTENT => $obj_select . "@main_btn",
           HIDDEN  => {
             'index'  => $index,
             'visual' => $FORM{visual} || 0,
           },
           NAME  => 'nms_obj_panel',
           ID    => 'nms_obj_panel',
           class => 'navbar-form navbar-right',
         }
      );

      print $html->element('div', $obj_select_form . $buttons, { class => 'navbar navbar-default' }) if !$FORM{IN_MODAL};
    }

    my $visual = $FORM{visual} || 'INFO';
    if ($visual eq 'INFO') {
      nms_obj_data({ ID => $obj_id });
    } 
    elsif ($visual eq 'STATS') {
      nms_snmp_stats({ ID => $obj_id });
    } 
    elsif ($visual eq 'MIB_BR') {
      mibs_browser({ ID => $obj_id });
    } 
    else {
      oid_table({ ID => $obj_id, SECT => $visual, OBJECTID  => $nms->[0]->{sysobjectid} });
    }
  }
  elsif ($Nms->{TOTAL} != 0) {
    my @status_bar = (
      "$lang{ALL}:index=$index",
      "$lang{ENABLED}:index=$index&STATUS=0",
      "$lang{DISABLED}:index=$index&STATUS=1",
    );
    my ($table) = result_former({
      INPUT_DATA      => $Nms,
      LIST            => $nms,
      BASE_FIELDS     => 1,
      DEFAULT_FIELDS  => 'IP, NAS_NAME, SYS_NAME, SYS_LOCATION, SYS_OBJECTID, STATUS',
      HIDDEN_FIELDS   => 'NAS_ID,ID,RO_COMMUNITY,RW_COMMUNITY',
      FUNCTION_FIELDS => 'change,del',
      EXT_TITLES      => {
        ip       => 'IP',
        name     => "$lang{NAME} NAS",
      },
      FILTER_COLS  => {
        ip          => "search_link:nms_obj:,ID",
        name        => "search_link:form_nas:,NAS_ID",
        sysobjectid => "search_link:sysobjectid_table:,SYSOBJECTID",
      },
      SELECT_VALUE    => { sysobjectid => \%$oid_hash },
      TABLE => {
        caption    => ($attr->{MONIT})? $html->color_mark($lang{DISABLED},'#FF0000') : "$lang{LIST} - $lang{EQUIPMENT}",
        qs         => $pages_qs,
        ID         => 'OBJ_LIST',
        header     => (!$attr->{MONIT})? $html->table_header(\@status_bar):undef,
        DATA_TABLE => {
          lengthMenu => [[28, 52, -1],[28, 52, $lang{ALL}]],
          ordering   => undef,
          searching  => ($attr->{MONIT})? undef : 'true',
          paging     => ($attr->{MONIT})? undef : 'true'
        }
      },
      MAKE_ROWS       => 1,
      SKIP_USER_TITLE => 1,
      SKIP_PAGES      => 1,
      TOTAL           => ($attr->{MONIT})? 0 : 1,
      OUTPUT2RETURN   => 1
    });
    return $table->show() if $attr->{MONIT};
    print $table;
  }
  return 1;
}

#**********************************************************

=head2 nms_obj_data()

=cut

#**********************************************************
sub nms_obj_data {

  my ($attr) = @_;

  my $prm = load_mibs({ ID => $attr->{ID}});
  my $info = $Nms->oids_list(
    {
      COLS_NAME => 1,
      OBJECTID  => $prm->{sysobjectid},
      TYPE      => 'scalar',
      LABEL     => '_SHOW',
      IID       => '_SHOW',
    }
  );
  if ($attr->{OID_ID}){
    $info = $Nms->oids_rows_list(
        {
          COLS_NAME => 1,
          ID        => $attr->{OID_ID},
          LABEL     => '_SHOW',
        }
      );
  }
  my @vars;
  foreach my $b (@$info) {
    push @vars, [$b->{label},$b->{iid} || $attr->{IID} || 0]
  }
  $snmpparms{UseSprintValue} = 1;
  $snmpparms{Community} = $attr->{COMMUNITY} || $conf{NMS_COMMUNITY_RO};
  my $sess = SNMP::Session->new(DestHost => $prm->{ip}, %snmpparms);

  my $vl = SNMP::VarList->new(@vars);
  my @result = $sess->get($vl);
  if ( $sess->{ErrorNum} ) {
    return $html->message('err', $lang{ERROR}, $sess->{ErrorStr});
  }

  my $table = $html->table(
    {
      #caption     => "$lang{LAST_UPDATE}: $info->[0]->{info_time}",
      width       => '100%',
      title_plain => [ $lang{PARAMS}, $lang{VALUE} ],
      cols_align  => [ 'left', 'left' ],
      ID          => 'EQUIPMENT_INFO',
    }
  );

  foreach my $val (@vars) {
  my $edit = ($SNMP::MIB{$val->[0]}{'access'} && $SNMP::MIB{$val->[0]}{'access'} =~ /ReadWrite|WriteOnly/)?
    $html->button( $lang{CHANGE}, undef,{
      JAVASCRIPT     => '',
      SKIP_HREF      => 1,
      NO_LINK_FORMER => 1,
      class          => "change",
      title          => $lang{ADD},
      ex_params      => qq/onclick=\"loadRawToModal('?get_index=nms_obj$pages_qs&header=2&visual=INFO&SET=$val->[0]&VAL=$val->[2]')\"/
    }) :'';
  $table->addrow($html->b($val->[0]), $val->[2], $edit);
  }

  print $table->show();

  return 1;
}

#**********************************************************

=head2 oid_table()

=cut

#**********************************************************
sub oid_table {

  my ($attr) = @_;

  my $info = $Nms->obj_list({
    COLS_NAME    => 1,
    ID           => $FORM{ID}||$attr->{ID},
    IP           => '_SHOW',
    SYS_OBJECTID => '_SHOW',
    }
  );

  my $prm = load_mibs({ ID => $attr->{ID}});
  my $tbl = $Nms->oids_list(
    {
      COLS_NAME => 1,
      SECTION   => $FORM{SECT}||$attr->{SECT},
      OBJECTID  => $prm->{sysobjectid},
      TYPE      => 'table',
      LABEL     => '_SHOW',
    }
  );
 
  my @tab_cont;
  my @header_arr;

  foreach my $t (@$tbl) {
    my $rows = $Nms->oids_rows_list({ ID => $t->{id} });
    my @vars;
    foreach my $row (@$rows) {
      push @vars, $row->[1];
    }

    push @tab_cont, $html->element('div', nms_snmp_table({
      SECT => $attr->{SECT},
      OID => $t->{label},
      columns => [ @vars ],
      IP => $info->[0]->{ip}
    }), { id => $t->{label}, class => "tab-pane fade" . (( @tab_cont < 1 )?'in active':'') });
    push @header_arr, "$t->{label}:#$t->{label}:data-toggle='tab'"; 
  }

  my $buttons = $html->table_header( \@header_arr, { TABS => 1 } );
  my $edit = $html->button($lang{EDIT}, "index=$index&edit=1", { ICON => 'fa fa-pencil-square-o', });
  my $tab = $html->element('div', "@tab_cont", { class => 'tab-content' });

  print $buttons . $tab;

  return 1;
}

#**********************************************************

=head2 nms_snmp_set()

=cut

#**********************************************************
sub nms_snmp_set {

  my ($attr) = @_;
  my $prm = load_mibs({ ID => $attr->{ID} });
  if ($FORM{IN_MODAL}){
    my %enums = oid_enums($attr->{LABEL});
    my %vals = reverse %enums;
    print $html->form_main({
      CONTENT =>
        (($FORM{IID})? label_w_txt('IID',$attr->{IID}) : '').
        label_w_txt('LABEL',$attr->{LABEL}).
        label_w_txt('VALUE', $vals{$attr->{VALUE}}|| $attr->{VALUE} || 0, {
          INP    => (oid_enums($attr->{LABEL}))? 'select' : 'input',
          SELECT => (oid_enums($attr->{LABEL}))? \%enums : '',
          RCOL => 8
        }).
        label_w_txt(undef, $html->form_input( 'SET', $lang{CHANGE}, {
            TYPE => 'SUBMIT'
          }) . "	" .
						$html->button( $lang{CANCEL}, undef,{
              SKIP_HREF => 1,
              ex_params =>qq/data-dismiss='modal'/,
              class => 'btn btn-default' }), {RCOL => 8}),
	    METHOD  => 'GET',
    	HIDDEN  => {
        'index'  => $index,
        'visual' => $FORM{visual},
        'ID'     => $attr->{ID},
        'LABEL'  => $attr->{LABEL},
        'IID'    => $attr->{IID}
     },
      class => 'form-horizontal'
  	});
    return 1
  }
  $snmpparms{Community} = $conf{NMS_COMMUNITY_RW};
  my $sess = SNMP::Session->new(DestHost => $prm->{ip}, %snmpparms);
  my $vb = SNMP::Varbind->new([$attr->{LABEL},$attr->{IID}||0,$attr->{VALUE}]);
  $sess->set($vb);
  if ( $sess->{ErrorNum} ) {
    return $html->message('err', $lang{ERROR}, $sess->{ErrorStr});
  }

  return 1;
}

#**********************************************************

=head2 nms_snmp_table()
=cut

#**********************************************************
sub nms_snmp_table {

  my ($attr) = @_;
  $snmpparms{UseSprintValue} = 1;
  $snmpparms{Community} = $attr->{COMMUNITY} || $conf{NMS_COMMUNITY_RO};
  my $sess = SNMP::Session->new(DestHost => $attr->{IP},%snmpparms);

  if (!$attr->{columns}){
	    foreach my $c (sort { $b <=> $a } @{$SNMP::MIB{$attr->{OID}}{children}[0]{children}}) {
			push @{$attr->{columns}}, $c->{'label'};
	    }
  }

  my $results = $sess->gettable( $attr->{OID}, columns => [@{$attr->{columns}}] );
  if ( $sess->{ErrorNum} ) {
	return $html->message('err', $lang{ERROR}, $sess->{ErrStr});
  }
 
  my $table = $html->table(
    {
      ID          => $attr->{OID},
      title_plain => [ @{$attr->{columns}} ],
      DATA_TABLE  => {
        ordering   => undef,
        lengthMenu => [[28, 52, -1],[28, 52, $lang{ALL}]],
      }
    }
  );

  my $visual = ($FORM{visual})? "&visual=$FORM{visual}": '';
  foreach my $var (sort { ($a =~ /^\d+$/ &&  $b =~ /^\d+$/) ? $a <=> $b : $a cmp $b } keys %$results) {
	  my @row = ();
	  foreach my $ind (@{$attr->{columns}}){
      if ( ($SNMP::MIB{$ind}{syntax} eq 'PortList') && $results->{$var}->{$ind} ){
  			$results->{$var}->{$ind} =~ s/"|\n//g;
  			my @in_hex = split(/ /, $results->{$var}->{$ind});
  			my $index='';
  			foreach my $hex (@in_hex){
  				$index .= sprintf( "%08b", hex($hex));
  			}
  	    $results->{$var}->{$ind} = '';
  			my $offset = 0;
        my $result = index($index, 1, $offset);
        while ($result != - 1) {
          $result = index($index, 1, $offset);
          $offset = $result + 1;
          $results->{$var}->{$ind} .= "$offset " if ( $offset > 0 );
        }
  		}
  		if ( $SNMP::MIB{$ind}{syntax} eq 'MacAddress'){
  			$results->{$var}->{$ind} = join(':', unpack("H2H2H2H2H2H2", $results->{$var}->{$ind}));
  		}
      if ( $SNMP::MIB{$ind}{access} && $SNMP::MIB{$ind}{access} =~ /ReadWrite|WriteOnly/ ){
        my $btn = $html->element( 'a', $html->element( 'span', undef, {
          class =>'glyphicon glyphicon-pencil pull-right'
        }), {
          class   => 'col-xs-3',
          title   => $lang{CHANGE},
          onclick => "ChangeVal('$ind','$results->{$var}->{$ind}','$var')",
        }) . $results->{$var}->{$ind} ;
        push @row, $btn;
  		}
      elsif ( $SNMP::MIB{$ind}{type} && $SNMP::MIB{$ind}{type} =~ /COUNTER|GAUGE/ ){
        my $btn = $html->element( 'a', $html->element( 'span', undef, {
          class =>'glyphicon glyphicon-signal pull-right'
        }), {
          class   => 'col-xs-3',
          title   => $lang{STATS},
          onclick => "ChangeStat('$ind','$var')",
        }) . $results->{$var}->{$ind} ;
        push @row, $btn;
  		}
      else {
        push @row,  $results->{$var}->{$ind};
      }
  	}
  	if ( $row[1]) {
  		$table->addrow(@row);
  	}
  }
  print qq(
     <script>
     function ChangeVal(Ind,Val,Var){
       var url = '?get_index=nms_obj$pages_qs&header=2$visual&SET=' + Ind + '&VAL=' + Val + '&IID=' + Var;
       loadRawToModal(url);
     };
     function ChangeStat(Ind,Var){
       var url = '?get_index=nms_obj$pages_qs&header=2$visual&STAT=' + Ind + '&IID=' + Var;
       loadRawToModal(url);
     };
    </script>
  ); 

  return $table->show();
}

#**********************************************************

=head2 nms_show()

=cut

#**********************************************************
sub nms_show {
  my ($attr) = @_;
  $snmpparms{UseSprintValue} = 1;
  my $table = $html->table();
  $table->addrow($html->b($lang{NAME}), $SNMP::MIB{$attr->{OID}}{label});
  $table->addrow($html->b('objectID'), $SNMP::MIB{$attr->{OID}}{objectID});
  $table->addrow($html->b($lang{TYPE}), $SNMP::MIB{$attr->{OID}}{type}) if $SNMP::MIB{$attr->{OID}}{type};
  $table->addrow($html->b('Module'), $SNMP::MIB{$attr->{OID}}{moduleID});
  $table->addrow($html->b($lang{ACCESS}), $SNMP::MIB{$attr->{OID}}{access});
  $table->addrow($html->b('Syntax'), $SNMP::MIB{$attr->{OID}}{syntax}) if $SNMP::MIB{$attr->{OID}}{syntax};
  $table->addrow($html->b($lang{RANGE}), "$SNMP::MIB{$attr->{OID}}{ranges}[0]{low} .. $SNMP::MIB{$attr->{OID}}{ranges}[0]{high}") 
      if $SNMP::MIB{$attr->{OID}}{ranges}[0];
  $table->addrow($html->b($lang{DESCRIBE}), $SNMP::MIB{$attr->{OID}}{description}) if $SNMP::MIB{$attr->{OID}}{description};
  $table->addrow($html->b('Reference'), $SNMP::MIB{$attr->{OID}}{reference}) if $SNMP::MIB{$attr->{OID}}{reference};
  $table->addrow($html->b('Index(es)'), "@{$SNMP::MIB{$attr->{OID}}{indexes}}") if $SNMP::MIB{$attr->{OID}}{indexes}[0];
  $table->addrow($html->b('Value List'), oid_enums($attr->{OID},{STR=>1})) if keys %{$SNMP::MIB{$attr->{OID}}{enums}};
  if ($attr->{EDIT} == 0){
    my $type = ($SNMP::MIB{$attr->{OID}}{children}[0]{indexes}[0])? 'table' : 'scalar';
    my $button = $html->button( $lang{ADD}, undef, {
      JAVASCRIPT     => '',
      SKIP_HREF      => 1,
      NO_LINK_FORMER => 1,
      class          => "btn btn-default",
      title          => $lang{ADD},
      ex_params      => qq/onclick=addLink('$attr->{OID}','$type') /
    });
    $table->addrow($button, '');
  }
   
  return $table->show();
}
#**********************************************************

=head2 mibs_browser()

=cut

#**********************************************************
sub mibs_browser {

  my ($attr) = @_;

  my $obj;
  my $root_index = get_function_index('mibs_browser');
  my $mods_index = get_function_index('modules_table');
  my $ID = $attr->{ID} || $FORM{ID} || $FORM{GET} || $FORM{WALK} || $FORM{TABLE} || $FORM{SHOW} || 0 ;
  $pages_qs = $pages_qs . "&ID=$ID";
  
  if ($FORM{OID}){
    $SNMP::save_descriptions = 1;
    $obj = load_mibs({ OBJECTID => $FORM{OBJECTID}, ID => $ID });
    print nms_show({ OID => $FORM{OID}, EDIT => $ID });
    if ($FORM{GET}){
      $snmpparms{UseSprintValue} = 1;
      my $sess = SNMP::Session->new(DestHost => $obj->{ip}, %snmpparms);
      my $iid = $attr->{IID} || 0;
      my $result = $sess->get([ $FORM{OID}, $iid ]);
      if ( $sess->{ErrorNum} ) {
        return $html->message('err', $lang{ERROR}, $sess->{ErrorStr});
      }
      my $result_tbl = $html->table({});
      $result_tbl->addrow($html->b($lang{RESULT}), $result);
      print $result_tbl->show();
    } 
    elsif ($FORM{WALK}){
      my $sess = SNMP::Session->new(DestHost => $obj->{ip}, %snmpparms);
      my @result = $sess->bulkwalk(0, 1,[ $FORM{OID} ]);
      if ( $sess->{ErrorNum} ) {
        return $html->message('err', $lang{ERROR}, $sess->{ErrorStr});
      }
      my $result_tbl = $html->table({});
      foreach my $val (@{$result[0]}) {
        my $edit = $html->button( $lang{CHANGE}, "index=$index$pages_qs&OID=$FORM{OID}",
             { MESSAGE => "$lang{CHANGE} $SNMP::MIB{$FORM{OID}}{label}",
               TEXT    => $lang{CHANGE},
               class   => 'change'
             });
        $result_tbl->addrow(@$val, ($SNMP::MIB{$FORM{OID}}{access} eq 'ReadWrite')? $edit :'')
      }
      print $result_tbl->show();
    } 
    elsif ($FORM{TABLE}){
      print nms_snmp_table({ IP => $obj->{ip}, OID => $FORM{OID}});
    } 
    elsif ($FORM{SET}){
      nms_snmp_set({ IP => $obj->{ip}, OID => $FORM{OID}});
    }
    return 1;
  }

  $obj = load_mibs({ OBJECTID => $FORM{OBJECTID}, ID => $ID });
  my $OBJECTID = $FORM{OBJECTID} || $obj->{sysobjectid};

  my $res = $html->element('div', '',
                { 
                id => 'RESULT',
                class => 'col-md-9 text-left',
                style => 'overflow-y:scroll;overflow-x:scroll;height:75vh;outline: 1px solid silver'
              });

  my $mod_btn = $html->button($lang{MODULES}, "index=$mods_index&OBJECTID=$OBJECTID", {class =>"btn btn-primary btn-sm"});
  my $search = $html->element('input', '', { 
    class => 'search-input form-control input-sm',
    placeholder => 'press Enter for search'
  });
  my $funct_div = $html->element('div', $search ."   ". $mod_btn, { class => 'form-inline' } );
  my $tree = $html->element('div', $funct_div . mibs_tree(),
                  { 
                  class => 'col-md-3',
                  style => 'overflow-y: scroll;height:75vh;outline: 1px solid silver'
                });
  my $scr = qq(
   <script>
    var id = '$ID';

    function renewLeftBox(itemName,Action,id,iid){
    iid = iid ? iid : 0 ;
    var url = 'index.cgi?qindex=$root_index&OBJECTID=$OBJECTID&header=2&OID=' + itemName + '&IID=' + iid + '&' + Action + '=' + id;
      jQuery('#RESULT').load(url);
    };
    jQuery('#MY_TREE').on("changed.jstree", function (e, data) {
        renewLeftBox(data.instance.get_node(data.selected[0]).text,'SHOW', id)
    });
    jQuery(".search-input").keypress(function(e) {
      if (e.which == 13) {
        var searchString = jQuery(this).val();
        console.log(searchString);
        jQuery('#MY_TREE').jstree('search', searchString);
      }
    });
  	jQuery.jstree.defaults.contextmenu.items = { };
    jQuery('#MY_TREE').on('contextmenu', '.jstree-anchor', function (e) {
  	});
  </script>); 

  print $html->element('div', $tree.$res,{class=>'row col-md-12'}) . $scr;
  return 1;
}

#**********************************************************

=head2 nms_snmp_stats()

=cut

#**********************************************************
sub nms_snmp_stats {
  
  my ($attr) = @_;
  use Time::Local;
  load_pmodule2('Redis');

  my $redis = Redis->new(
          server => $conf{REDIS_SERV},
          encoding => undef,
  );

  if ($attr->{DEL_TR}){
    $Nms->trigger_del($attr->{DEL_TR});
    return 1
  }
  if ($attr->{ADD_TR}){
    $Nms->trigger_add({
      OBJ_ID => $attr->{OBJ_ID},
      LABEL  => $attr->{LABEL},
      IID    => $attr->{ADD_TR},
      MONIT  => $attr->{MONIT}
    });
    print Dumper $attr;
    return 1
  }
  my $stats = $Nms->triggers_list({
      COLS_NAME => 1,
      OBJ_ID    => $attr->{OBJ_ID},
      LABEL     => $attr->{LABEL} || '_SHOW',
      IID       => $attr->{IID} || '_SHOW',
      MONIT     => '_SHOW',
      SYS_NAME  => '_SHOW',
  });

  if (!$stats && $FORM{IN_MODAL}) {
    my $frm = label_w_txt('IID',$attr->{IID});
    $frm .= label_w_txt('LABEL',$attr->{LABEL});
    $frm .= label_w_txt('MONIT',$html->form_input('MONIT', 1, {
      TYPE => 'checkbox',
      STATE => $stats->[0]->{monit}||undef
    }));
    $frm .= label_w_txt(undef, 
    $html->element('button', $lang{ADD}, {
        class => 'btn btn-info',
        'data-dismiss' => 'modal',
        type    =>'button',
        onclick => "addTrigger()"
    }) .
    $html->element('button', $lang{CANCEL}, {
        class => 'btn btn-default',
        'data-dismiss' => 'modal',
        type    =>'button',
     }), {RCOL => 8});

    print $html->element('form', $frm , { class => 'form-horizontal' });
    print qq(
    <script>
    function addTrigger(){
      var monit;
      if(jQuery("input#MONIT").is(':checked')) {
        monit = '&MONIT=1';
      }
      jQuery.get('?get_index=nms_obj&header=2&ID=$attr->{OBJ_ID}&STAT=$attr->{LABEL}&ADD_TR=$attr->{IID}' + monit);
    };
    </script>
    );
    return 1
  }
  elsif (!$stats) {
    return 1
  }

  my $to_date = time;
  my $from_date = time-21600;
  if ($FORM{TO_DATE}){
    my ($year,$mon,$mday,$hour,$min) = split(/[\s\-:]+/, $FORM{TO_DATE});
    $to_date = timelocal(0,$min,$hour,$mday,$mon-1,$year);
  }
  if ($FORM{TO_DATE}){
    my ($year,$mon,$mday,$hour,$min) = split(/[\s\-:]+/, $FORM{FROM_DATE});
    $from_date = timelocal(0,$min,$hour,$mday,$mon-1,$year);
  }
  
  my %ind;
  my %params;
  foreach my $key ( @$stats ) {
    my @list = $redis->zrangebyscore("$key->{id}", $from_date, $to_date, 'WITHSCORES' );
    foreach my $val ( 0..@list-2 ) {
      if ( $val%2 == 1 ){
        my $value = sprintf("%.2f", ($list[$val+1] - $list[$val-1]) / ($list[$val+2] - $list[$val]) / 1048576 * 8);
        push  @{$ind{$key->{iid}}}, ({ $key->{label} => $value, y => strftime("%Y-%m-%d %T", localtime($list[$val])) });
      }
    }
    push  @{$params{$key->{iid}}}, $key->{label};
  };

  my $PORT_SEL = $html->form_select(
    'PORT',
    {
      SELECTED  => $FORM{PORT},
      SEL_ARRAY => \@{ [ sort { $a <=> $b } keys %ind ] },
      NO_ID     => 1
    }
  );

  if (!$attr->{MONIT} && !$FORM{IN_MODAL}){
    print $html->form_main(
      {
        CONTENT => "$lang{PERIOD}: $lang{FROM} &nbsp" . $html->form_datetimepicker2('FROM_DATE') .
      "&nbsp $lang{TO} &nbsp" . $html->form_datetimepicker2('TO_DATE') .
      "&nbsp $lang{PORT}: " . $PORT_SEL . $html->form_input('SHOW', $lang{SHOW}, { TYPE => 'SUBMIT' }),
        METHOD  => 'GET',
        class   => 'form-inline',
        HIDDEN  => {
          index  => "$index",
          visual => 'STATS',
          ID => $attr->{ID} || $FORM{ID},
        },
      }
    );    
  }

  my $chart;
  foreach my $in (sort { $a <=> $b } keys %ind) {
    $chart .= $html->make_charts3("$stats->[0]->{sysname}: $lang{PORT} $in", 'Line', {
      data      => \@{$ind{$in}},
      ykeys     => \@{$params{$in}},
      xkey     => 'y',
      labels    => \@{$params{$in}},
      element   => $in,
      postUnits => 'Mb/s',
      hideHover => 'auto',
      resize    => 'true'
    });
  }
  my $del_btn = ($FORM{IN_MODAL})? $html->element('button', $lang{DEL} .' trigger', {
    class => 'btn btn-default',
    'data-dismiss' => 'modal',
    type    =>'button',
    onclick => "jQuery.get('?get_index=nms_obj&header=2&STAT=1&DEL_TR=$stats->[0]->{id}')"
  }) : '';

  return $chart if $attr->{MONIT};
  
  print $chart.$del_btn;
  return 1
}

#**********************************************************
=head2 label_w_txt($label,$text,$attr); - return formated text with label

  Arguments:
    $label - text of label
    $text 
    $attr -
      CTRL - for form with input control
      COLOR - color of label
      ID - 
      TYPE -
      LCOL
      RCOL
      
  Returns:
    String with element

=cut
#**********************************************************
sub label_w_txt {
	my ($label,$text,$attr) = @_;
	my $class = ($attr->{COLOR}) ? "label-$attr->{COLOR}" : '' ;
  $class = ($attr->{ICON})? ' has-feedback' : '' ;
  my $flabel =  $html->element(($attr->{INP})? 'span' : 'label', $label, {
    class => 'control-label col-sm-' . ($attr->{LCOL}||'2'),
    for => $attr->{ID} || $label
  });
  my %ex_attr = (
    class => ($attr->{INP})?'form-control':'form-control-static',
    id => $attr->{ID} || $label,
    name => $attr->{ID} || $label,
    type => $attr->{TYPE} || undef,
    placeholder => ($attr->{HOLDER})? $attr->{HOLDER} : undef
  );
  my @sels;
  if ($attr->{SELECT} && ref($attr->{SELECT}) eq 'ARRAY'){
    foreach my $opt (@{$attr->{SELECT}}){
      my $op = $html->element('option', $opt, { value => $opt});
      $op =~ s/<option /<option selected / if $text eq $opt ;
      push @sels, $op
    }
    $text = "@sels";
  }
  elsif ($attr->{SELECT} && ref($attr->{SELECT}) eq 'HASH') {
    while ( my ($key, $value) = each (%{$attr->{SELECT}}) ){
      my $op = $html->element('option', $value, { value => $key});
      $op =~ s/<option /<option selected / if $text eq $key ;
      push @sels, $op
    }
    $text = "@sels";
  }
  $ex_attr{value} = ($attr->{INP} && $attr->{INP} eq 'input')? $text : undef;
  $text = (!$attr->{INP} || $attr->{INP} ne 'input')? $text : '';
  my $ftext =  $html->element(($attr->{INP})?$attr->{INP}:'p', $text, \%ex_attr);
  $ftext .= $html->element('span', undef,
    {
      id    => $attr->{ID} || $label,
      class => $attr->{ICON} . ' form-control-feedback'
    }) if $attr->{ICON};
  $ftext = $html->element('div', $ftext, { class => 'col-sm-' . ($attr->{RCOL}||'3') . $class });
	
	return $html->element('div', $flabel.$ftext, { class => 'form-group' . $class });
}
#**********************************************************

=head2 sysobjectid_table()

=cut

#**********************************************************
sub sysobjectid_table {

  my ($attr) = @_;

    $LIST_PARAMS{OBJECTID} = $FORM{SYSOBJECTID};
#    $LIST_PARAMS{GROUP} = 'module';
    result_former({
      INPUT_DATA      => $Nms,
      FUNCTION        => 'sysobjectid_list',
    #  DEFAULT_FIELDS  => 'SYSORID, MODULE, STATUS',
      DEFAULT_FIELDS  => 'LABEL, OBJECTID',
      FUNCTION_FIELDS => 'modules_table:modules:objectid,oids_set:oids:objectid',
      SKIP_USER_TITLE => 1,
      FILTER_COLS  => {
#        ip   => "search_link:nms_obj:,ID",
      },
#     SELECT_VALUE    => { sysObjectID => \%ohash },
      TABLE => {
        caption => " ",
        qs      => ($FORM{SYSOBJECTID})? "$pages_qs&SYSOBJECTID=$FORM{SYSOBJECTID}" : $pages_qs,
        ID      => 'SYSOBJECTID_LIST',
      },
      MAKE_ROWS => 1,
      TOTAL     => 1
    });

  return 1;
}
#**********************************************************

=head2 modules_table()

=cut

#**********************************************************
sub modules_table {
  my ($attr) = @_;

  $LIST_PARAMS{OBJECTID} = $FORM{OBJECTID};
  $pages_qs = "$pages_qs&OBJECTID=$FORM{OBJECTID}";
  if ($FORM{del}){
    $Nms->module_del($FORM{del});
  }
  if ($FORM{SAVE}){
    $Nms->module_add({
      ID        => $FORM{ID}||'',
      MODULE    => $FORM{NAME},
      OBJECTID  => $FORM{OBJECTID},
      DESCR     => $FORM{DESCR},
      STATUS    => $FORM{STATUS} || 0
    } );
  }
  my $modules = $Nms->modules_list({ 
    ID        => $FORM{chg},
    MODULE    => '_SHOW',
    DESCR     => '_SHOW',
    STATUS    => '_SHOW',
    COLS_NAME => 1,
    %LIST_PARAMS,
  });
  if ($FORM{chg} || $FORM{add}){
    SNMP::addMibFiles(glob("../../var/snmp/mibs/private" . '/*'));
    my %mod;
    foreach my $oid (keys(%SNMP::MIB)) {
       $mod{$SNMP::MIB{$oid}{moduleID}} = '' if $SNMP::MIB{$oid}{moduleID}
    }
    my @mods = sort keys %mod;
  	my $NAME_SEL = $html->form_select(
      'NAME',
      	{
        		SELECTED  => $modules->[0]->{module}|| '',
        		SEL_ARRAY  => \@mods,
      	}
      );
    print $html->form_main({
          	CONTENT =>  label_w_txt($lang{DESCRIBE}, $modules->[0]->{descr}).
                        label_w_txt($lang{NAME}, $NAME_SEL).
                        label_w_txt($lang{STATUS}, $html->form_input('STATUS', 1, {
                            TYPE => 'checkbox',
                            STATE => $modules->[0]->{status}||undef
                          })
                          ).
                        label_w_txt(undef, $html->form_input( 'SAVE', ( $FORM{chg} )? $lang{CHANGE} : $lang{CREATE}, {
                            TYPE => 'SUBMIT'
                          }) . "	" .
      											$html->button($lang{CANCEL}, "index=$index$pages_qs", {class =>"btn btn-default"}),
      								  {RCOL => 3}),
      	    METHOD  => 'GET',
          	HIDDEN  => {
            				'index'    => $index,
            				'ID'       => $FORM{chg} || '',
                    'OBJECTID' => $FORM{OBJECTID},
                    'DESCR'    => $modules->[0]->{descr}
          				},
        	});
  }
  else{
    result_former({
      INPUT_DATA      => $Nms,
      LIST            => $modules,
      DEFAULT_FIELDS  => 'MODULE, DESCR, STATUS',
      HIDDEN_FIELDS   => 'OBJECTID',
      FUNCTION_FIELDS => 'change, del',
      SKIP_USER_TITLE => 1,
      STATUS_VALS     => [$lang{DISABLED}, $html->color_mark($lang{ACTIV}, 'text-success')],
      TABLE => {
        caption => "SNMP Modules",
        qs      => $pages_qs,
        ID      => 'MODULES_LIST',
        MENU    => "$lang{ADD}:index=$index$pages_qs&add=1:add",
      },
      MAKE_ROWS => 1,
      TOTAL     => 1
    });
  }

  return 1;
}

#**********************************************************
=head2 load_mibs($attr); - return formated text with label

=cut
#**********************************************************
sub load_mibs {
  my ($attr) = @_;
  if ($attr->{ALL}){
    SNMP::addMibFiles(glob('../../var/snmp/mibs/private' . '/*'));
  }
  else {
    my $nms;
    if ($attr->{ID}){
      $nms = $Nms->obj_list({
        COLS_NAME    => 1,
        ID           => $attr->{ID},
        IP           => '_SHOW',
        SYS_OBJECTID => '_SHOW',
        }
      );
    }
  
    my @mods;
    my $sys_mods = $Nms->modules_list({
      OBJECTID => $attr->{OBJECTID} || $nms->[0]->{sysobjectid},
      MODULE   => '_SHOW',
      STATUS   => 1
    });
    foreach my $val (@$sys_mods) {
      push @mods, $val->[0];
    }
    SNMP::loadModules(@mods);
    SNMP::initMib();
  
    return $nms->[0] if $attr->{ID};
  }
  return 1;
}

#**********************************************************

=head2 oid_enums()

=cut

#**********************************************************
sub oid_enums {
  my ($oid, $attr) = @_;
  my %enums;
  my $str = '';
  foreach my $el ( keys %{$SNMP::MIB{$oid}{enums}} ) {
    $enums{$SNMP::MIB{$oid}{enums}{$el}} = $el;
  }
  if ($attr){
    foreach my $key ( sort keys %enums ) {
      $str .= "$key = $enums{$key} </br>"
    }
    return $str;
  };

  return %enums;
}

#**********************************************************

=head2 mibs_tree()

=cut

#**********************************************************
sub mibs_tree {

  my ($attr) = @_;

  my %labels;
  my @tree_arr;
  foreach my $oid (sort keys(%SNMP::MIB)) {
    if ( $attr->{LABEL} || $attr->{SYNTAX} ) {
      if ( $attr->{SYNTAX} ) {
        $labels{$SNMP::MIB{$oid}{label}} = $SNMP::MIB{$oid}{objectID} if  $SNMP::MIB{$oid}{syntax} eq $attr->{SYNTAX}
      }
      else {
        foreach my $val ( @{$attr->{LABEL}} ) {
          $labels{$SNMP::MIB{$oid}{label}} = $SNMP::MIB{$oid}{objectID} if  $SNMP::MIB{$oid}{label} =~ /$val/
        }
      }
    }
    elsif ( $attr->{HASH} ) {
      $labels{substr($SNMP::MIB{$oid}{objectID},1)} = $SNMP::MIB{$oid}{label}
    }
    else {
      my $prev_id = ($SNMP::MIB{$oid}{parent})? $SNMP::MIB{$oid}{parent}{objectID} : '#' ;
      my $icon = '';
      my %type;
      if ( $SNMP::MIB{$oid}{children}[0]{indexes}[0] ){
        $type{type} = 'table';
      } 
      elsif ( $SNMP::MIB{$oid}{parent} && $SNMP::MIB{$oid}{parent}{indexes}[0]){
        $type{type} = 'row';
      } 
      elsif ( $SNMP::MIB{$oid}{type}){
        $type{type} = 'scalar';
      }
      push @tree_arr, ({
        id   => $SNMP::MIB{$oid}{objectID},
        text => $SNMP::MIB{$oid}{label},
        parent => $prev_id,
        %type
      });
    }
  }
  return \%labels if $attr->{LABEL} || $attr->{HASH} || $attr->{SYNTAX};
  return make_tree( @tree_arr );
}

#**********************************************************
=head2 make_tree($attr) - Make different charts

   If given only one series and X_TEXT as YYYY-MM, will build columned compare chart

   Arguments:
     $attr
       DATA    - Data array of hashes
   Result:
     TRUE or FALSE

=cut
#**********************************************************
sub make_tree {
  my (@data) = @_;
  my $result = '';
  my $TREE_ID = 'MY_TREE';
  my $DATA  = JSON->new->encode(\@data);
  
  $result.= qq{
    <link rel='stylesheet' href='/styles/lte_adm/plugins/jstree/themes/proton/style.min.css' />
    <script type='text/javascript' src='/styles/lte_adm/plugins/jstree/jstree.min.js'></script>
    <div id=$TREE_ID></div>
  };
  $result.= qq(
    <script>
      jQuery('#$TREE_ID').jstree({
    		'core' : {
          'themes': {
            'name': 'proton',
            'responsive': true
          },
          'data' : $DATA
        },
        'plugins' : [ 'contextmenu', 'types', 'search' ],
        'search': {
          'case_insensitive': true,
          'show_only_matches' : false
        },
        'contextmenu' : {
          'items' : customMenu
        },
        'types' : {
          'table' : {
                'icon' : 'glyphicon glyphicon-list-alt'
              },
          'row' : {
                'icon' : 'glyphicon glyphicon-option-horizontal'
              },
          'scalar' : {
                'icon' : 'glyphicon glyphicon-file'
              }
        }
    	});
      function customMenu(node) {
          var items = {
              Get: {
                  label: 'Get',
                  icon : 'glyphicon glyphicon-download',
                  action: function () {
                    renewLeftBox(node.text,'GET',id);
                  }
              },
              Table: { 
                  label: 'Table',
                  icon : 'glyphicon glyphicon-list-alt',
                  action: function () {
                    renewLeftBox(node.text,'TABLE',id);
                  }
              },
              Walk: { 
                  label: 'Walk',
                  icon : 'glyphicon glyphicon-circle-arrow-down',
                  action: function () {
                    renewLeftBox(node.text,'WALK',id);
                  }
              }
          };

          if (node.type === 'scalar') {
            delete items.Table;
            delete items.Walk;            
          }
          else if (node.type === 'row') {
            delete items.Get;
            delete items.Table;
          }
          else if (node.type === 'table') {
            delete items.Get;
          }
          else {
            delete items.Table;
            delete items.Walk;
            delete items.Get;
          }

          return items;
      }
	  </script>
   );

  return $result;
}

#**********************************************************

=head2 nms_monitor()

=cut

#**********************************************************
sub nms_monitor {
  my ($attr) = @_;
  my $traps_pg_rows = $FORM{FILTER} || 10;
  my $page = nms_obj({ STATUS => 1, MONIT => 1 });
  if ($page eq '1') {
    $page = nms_snmp_stats({ MONIT => 1 });
  }
  $page .= nms_traps({ PAGE_ROWS => 10, MONIT => 1 });

  my $scr = qq(
    <script type="text/javascript">
      var url = 'index.cgi?get_index=nms_monitor&header=2&REFRESH=1';
      var ref_timer = '';
      var timerId = '';
      function loadNowPlaying(){
        jQuery("#MONIT").load(url);
      }
      jQuery("input[name=toggle]").change(function(){
       if(jQuery(this).is(':checked')){
         ref_timer = (jQuery("#timer").val() >= 10 ) ? jQuery("#timer").val() : 60;
       //  alert(ref_timer);
         timerId = setInterval(function(){loadNowPlaying()}, ref_timer*1000);
       }
       else{
         clearInterval(timerId);
       }
      });
    </script>
  );
  my $refr = $html->element('label', $html->element('input', undef, {
        type => 'checkbox',
        name => 'toggle'
      }) . 'Refresh', { class=>'checkbox-inline' }) ;
  $refr .= $html->element('label', $html->element('input', undef, {
        type => 'number',
        min  => '10',
        id   => 'timer',
        placeholder => '60'
      }) . ' seconds', { class=>'checkbox-inline' }) ;
  print $html->element('div', $page, { ID => 'MONIT'} );
  print $refr . $scr if (!$FORM{REFRESH});

  return 1;
}

#**********************************************************

=head2 oids_set()

=cut

#**********************************************************
sub oids_set {
  my ($attr) = @_;

  load_mibs({ OBJECTID => $FORM{OBJECTID} });
  if ( $FORM{del} ) {
    $Nms->oid_del($FORM{del});
  }
  my $type = $FORM{oid_type} || 'main';
  
  if ( $FORM{chg} && $type ne 'main') {
    return oid_table_row_edit({ OID_ID => $FORM{chg}, OBJECTID => $FORM{OBJECTID} });
  }

  if ($FORM{OID} ) {
    my $sect = ($FORM{TYPE})? $FORM{TYPE} : $SNMP::MIB{$FORM{OID}}{parent}{label};
    my $id_num = $Nms->obj_oids_add({
      ID       => $FORM{OID_ID} || '',
      LABEL    => $FORM{OID},
      SECTION  => $sect,
      TYPE     => $FORM{oid_type} || '',
      OBJECTID => $FORM{OBJECTID},
      VALUE    => $FORM{VALUE},
    });
    if (!$FORM{TYPE}){
      print $id_num->{INSERT_ID};
      return 1
    }
  }

  my @header_arr = (
    "$lang{MAIN}:index=$index&oid_type=main&OBJECTID=$FORM{OBJECTID}$pages_qs",
    "TABLE:index=$index&oid_type=table&OBJECTID=$FORM{OBJECTID}$pages_qs",
    "SCALAR:index=$index&oid_type=scalar&OBJECTID=$FORM{OBJECTID}$pages_qs"
  );

  my $buttons = $html->table_header( \@header_arr, { TABS => 1 } );
  print $html->element('div', $buttons, { class => 'navbar navbar-default' });
  
  if ( ($FORM{add}  || $FORM{ID}) && $type ne 'main') {
    mibs_browser({EDIT => 1});
    print qq(
      <script>
        function addLink(oid,type){
          var link = '?get_index=oids_set&header=2&OBJECTID=$FORM{OBJECTID}';
          if ( type === 'table'){
            jQuery.get(link + '&OID=' + oid + '&oid_type=' + type, function(data){
              loadRawToModal(link + '&oid_type=' + type + '&chg=' + data);
            });
          }
          else {
            jQuery.get(link + '&OID=' + oid + '&oid_type=' + type);
          }
        };
      </script>
      );
  }
  else{
    $LIST_PARAMS{OBJECTID} = $FORM{OBJECTID};
    $LIST_PARAMS{TYPE} = $type;
    $LIST_PARAMS{ID} = $FORM{chg} || '_SHOW';
    my ($table,$list) = result_former({
      INPUT_DATA      => $Nms,
      FUNCTION        => 'oids_list',
      DEFAULT_FIELDS  => 'SECTION,LABEL,IID,TYPE,ACCESS,VALUE',
      FUNCTION_FIELDS => ($type eq 'table' || $type eq 'main')? "change,del" : 'del',
      HIDDEN_FIELDS   => 'ID,OBJECTID',
      EXT_TITLES      => {
        type     => "$lang{TYPE}",
       },
      SKIP_USER_TITLE => 1,
      TABLE           => {
       qs      => "$pages_qs&OBJECTID=$FORM{OBJECTID}&oid_type=$type",
       ID      => 'OID_LIST',
       caption => $SNMP::MIB{$FORM{OBJECTID}}{label},
       MENU => "$lang{ADD}:index=$index$pages_qs&OBJECTID=$FORM{OBJECTID}&oid_type=$type&add=1:add",
      },
      MAKE_ROWS => 1,
      TOTAL     => 1,
      OUTPUT2RETURN     => 1
    });
    if ( ($FORM{add} || $FORM{chg} )  && $type eq 'main' ) {
      my %labels;
      foreach my $oid (keys(%SNMP::MIB)) {
        if  ( $SNMP::MIB{$oid}{label} =~ /Reset|Write|Save|Reboot|write|reset|operation/ && !$SNMP::MIB{$oid}{children}[0]{label}
        && ($SNMP::MIB{$oid}{access} && $SNMP::MIB{$oid}{access} =~ /ReadWrite|WriteOnly/) ) {
          my %enums = oid_enums($SNMP::MIB{$oid}{label});
          $labels{$SNMP::MIB{$oid}{label}} = (%enums) ? \%enums: undef;
        }
      }
      my $vals = JSON->new->indent->encode(\%labels);
      my @keys = sort keys %labels;
      print $html->form_main({
      	CONTENT =>  
          label_w_txt('TYPE',$list->[0]->{section}|| 'write', {INP=>'select', SELECT => ['write', 'reboot']}).
          label_w_txt('OID',$list->[0]->{label}|| 0, {INP=>'select', SELECT => \@keys}).
          label_w_txt('VALUE', $list->[0]->{value}|| 0, {
            INP    => ($list->[0]->{label} && $labels{$list->[0]->{label}})? 'select' : 'input',
            SELECT => ($list->[0]->{label} && $labels{$list->[0]->{label}})? $labels{$list->[0]->{label}} : ''
          }).
          label_w_txt(undef, $html->form_input( 'SAVE', ($FORM{chg})? $lang{CHANGE} : $lang{CREATE}, {
              TYPE => 'SUBMIT'
            }) . "	" .
							$html->button($lang{CANCEL}, "index=$index$pages_qs", {class =>"btn btn-default"}),
				  {RCOL => 3}),
  	    METHOD  => 'GET',
      	HIDDEN  => {
          'index'    => $index,
          'oid_type' => 'main',
          'OBJECTID' => $FORM{OBJECTID},
          'OID_ID' => $FORM{chg}
       },
        class => 'form-horizontal'
    	});
      print qq(
        <script>
        var selectValues = $vals;
        jQuery('select#OID').on('change', function() {
          if (selectValues[this.value] === null ) {
            jQuery('select#VALUE').chosen("destroy");
            jQuery('select#VALUE').replaceWith("<input class='form-control' name='VALUE' id='VALUE'></input>");
          }
          else {
            jQuery('input#VALUE').replaceWith("<select class='form-control' name='VALUE' id='VALUE'></select>");
            jQuery('select#VALUE').chosen();
            jQuery('select#VALUE').empty();
            jQuery.each(selectValues[this.value], function(key, value) {
              jQuery('select#VALUE').append('<option value=' + key + '>' + value + '<option>');
            });
            jQuery('select#VALUE').trigger("chosen:updated");
          }
        });
        </script>
      );
    }
    else {
      print $table
    }
  }

  return 1;
}

#**********************************************************

=head2 oid_table_row_edit()

=cut

#**********************************************************
sub oid_table_row_edit {

  my ($attr) = @_;

  if ( $FORM{OID_DEL} ) {
    $Nms->oid_row_del({ 
      LABEL  => $FORM{OID_DEL},
      OID_ID => $attr->{OID_ID}
    });
    return 1
  }
  if ( $FORM{ADD} ) {
    $Nms->oid_row_add({
      ID => $attr->{OID_ID},
      LABEL  => $FORM{ADD},
    });
  } 

  my $oid = $Nms->oids_list({
    COLS_NAME  => 1,
    ID         => $attr->{OID_ID},
    SECTION    => '_SHOW',
    OBJECTID   => $attr->{OBJECTID},
    LABEL      => '_SHOW',
    IID        => '_SHOW',
    TYPE       => '_SHOW',
    ACCESS     => '_SHOW'
  });
  $oid = $oid->[0];

  my $rows = $Nms->oids_rows_list({
    COLS_NAME  => 0,
    ID         => $attr->{OID_ID},
    LABEL      => '_SHOW',
    OBJECTID   => '_SHOW',
    LIST2HASH  => 'label, objectid'
  });

  my @colls;
  foreach my $coll (@{$SNMP::MIB{$oid->{label}}{children}[0]{children}}) {
    my $state = ( exists $rows->{$coll->{label}} ) ? 1 : undef ;
    push @colls, label_w_txt( $coll->{label}, $html->form_input($coll->{label}, $state, { TYPE => 'checkbox', STATE => $state }),{LCOL => 4,RCOL => 2} );
  }
	print $html->element('div', $html->element('h4', $oid->{label}, { class => 'modal-title' }),
    { class => 'modal-header' });
  my $btn = $html->element('button', ($FORM{IN_MODAL})? $lang{CLOSE}: $lang{BACK}, {
    class => 'btn btn-default',
    'data-dismiss' => 'modal',
    type=>'button',
    onclick => (!$FORM{IN_MODAL})? 'goBack()':''
   });
  print $html->element('div', $html->element('form',"@colls" . $btn , { class => 'form-horizontal' }), { class => 'modal-body' });
  
  my $scr = qq(
         <script>
         jQuery(':checkbox').change(function(){
             var link = '?get_index=oids_set&header=2&oid_type=table&OBJECTID=$attr->{OBJECTID}';
             if(jQuery(this).prop('checked')) {
               jQuery.get(link + '&chg=$attr->{OID_ID}' + '&ADD=' + jQuery(this).prop('id'), function(data){
                 //alert(data);
               });
             }
             else {
               jQuery.get(link + '&chg=$attr->{OID_ID}' + '&OID_DEL=' + jQuery(this).prop('id'), function(data){
                 //alert(data);
               });
             }
         });
         function goBack() {
             window.history.back();
         }
         </script>
         );
  print $scr;
  return 1;
}


1;